var FAKE = FAKE || {};

FAKE.gold = 123456;
FAKE.gem = 789;
FAKE.uid = 'UNSTOPABLE_13';
FAKE.trophy = 93774;
FAKE.chests = [
    {
        openTimeRequired: 3 * 60 * 60 * 1000,
        openTimeStarted: 0,
        golds: [10, 20],
        cards: [4, 5],
        rarities: [1, 2],
    },
    {
        openTimeRequired: 3 * 60 * 60 * 1000,
        openTimeStarted: 1668007241022,
        golds: [100, 200],
        cards: [40, 50],
        rarities: [1, 2, 3],
    },
    {
        openTimeRequired: 3 * 60 * 60 * 1000,
        openTimeStarted: null,
        golds: [200, 400],
        cards: [400, 500],
        rarities: [1, 2, 3, 4],
    },
    undefined,
];
FAKE.deck = [
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
];
FAKE.collection = [
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
];
