fake.deck = [
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
];
fake.collection = [
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 17,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 20,
        texture: asset.cardTowerCannon_png,
    },
    {
        energy: 6,
        rarity: 0,
        level: 23,
        fragment: 27,
        reqFrag: 0,
        texture: asset.cardTowerCannon_png,
    },
];
