const GAME_CONFIG = {
    DEFAULT_DELTA_TIME: 0.016,
    TIME_PER_MONSTER_IN_WAVE: 0.4,
    RULE_A: 1,
    RULE_B: 2,
    MAP_RATIO : 15 / 8,
    NUM_CARD_PLAYABLE : 4,
    ENERGY_DESTROY_CARD : 5,
    TICK_FOR_DELAY_TOWER : 60,
    TICK_FOR_DELAY_SPELL_FALL : 30,
    MAX_HP: 60,
    MAX_WAVE : 20,
    START_ENERGY : 15,
    MAX_ENERGY : 30,
    MAX_VALUE : 99999,
    TIME_WAVE: 20,

    RENDER_START_Z_ORDER_VALUE: 999
}