const ACTION_CODE = {
    NEXT_WAVE_ACTION: 0,
    ACTIVATE_CARD_ACTION: 1,
    ACTIVATE_SPELL_ACTION: 2
}

const ACTION_DESERIALIZER = {}

ACTION_DESERIALIZER[ACTION_CODE.NEXT_WAVE_ACTION] = NextWaveAction.deserializer
ACTION_DESERIALIZER[ACTION_CODE.ACTIVATE_CARD_ACTION] = ActivateCardAction.deserializer
ACTION_DESERIALIZER[ACTION_CODE.ACTIVATE_SPELL_ACTION] = ActivateSpellAction.deserializer

const ACTION_DESERIALIZER_FROM_ARR = {}

ACTION_DESERIALIZER_FROM_ARR[ACTION_CODE.NEXT_WAVE_ACTION] = NextWaveAction.deserializerArr
ACTION_DESERIALIZER_FROM_ARR[ACTION_CODE.ACTIVATE_CARD_ACTION] = ActivateCardAction.deserializerArr
ACTION_DESERIALIZER_FROM_ARR[ACTION_CODE.ACTIVATE_SPELL_ACTION] = ActivateSpellAction.deserializerArr