const ACTION_CODE = {
    NEXT_WAVE_ACTION: 0,
    ACTIVATE_CARD_ACTION: 1,
    CHANGE_PRIORITIZED_TARGET_ACTION: 2,
}

const ACTION_DESERIALIZER = {}

ACTION_DESERIALIZER[ACTION_CODE.NEXT_WAVE_ACTION] = NextWaveAction.deserializer
ACTION_DESERIALIZER[ACTION_CODE.ACTIVATE_CARD_ACTION] = ActivateCardAction.deserializer
ACTION_DESERIALIZER[ACTION_CODE.CHANGE_PRIORITIZED_TARGET_ACTION] = ChangePrioritizedTargetAction.deserializer
