const GAME_CONFIG = {
    CELLSIZE: 60,
    HOME_STATE: 0,
    DES_STATE: 99,
    ENEMY_STATE: 1,
    CHEST_STATE: 5,
    SHOP_STATE: 2,
    ITEM_POTION: 1,
    ITEM_WEAPON: 2,
    ITEM_GATE: 3,
    ITEM_DIS_MIN: 100,

    RENDER_START_Z_ORDER_VALUE: 999
}