const GAME_CONFIG = {
    CELLSIZE: 60,
    HOME_STATE: 0,
    DES_STATE: 99,
    ENEMY_STATE: 1,
    CHEST_STATE: 5,
    SPECIAL_STATE: 10,
    SHOP_STATE: 2,

    ITEM_POTION: 1,
    ITEM_WEAPON: 2,
    ITEM_GATE: 3,
    ITEM_CHEST: 4,
    ITEM_SHOPBACK: 10,

    ITEM_DIS_MIN: 100,

    MAP_BLOCK: 1,
    MAP_BOX: 5,
    MAP_BOOMM1: 6,
    MAP_BOOMM2: 7,
    MAP_BOOMM3: 8,

    STATE_ONSTART: 0,
    STATE_FIGHTING: 1,
    STATE_MOVING:2,

    DIS_CHECK_COLISION: 0.5,

    RENDER_START_Z_ORDER_VALUE: 999
}